const ADMIN_GETS_ALL_USERS_REQUEST = "ADMIN_GETS_ALL_USERS_REQUEST";
const ADMIN_GETS_STATISTICS_DATA = "ADMIN_GETS_STATISTICS_DATA ";
const ADMIN_GETS_ALL_USERS = "ADMIN_GETS_ALL_USERS";

export {
  ADMIN_GETS_ALL_USERS_REQUEST,
  ADMIN_GETS_STATISTICS_DATA,
  ADMIN_GETS_ALL_USERS,
};
