const ADMIN_GETS_ALL_USERS_REQUEST = "ADMIN_GETS_ALL_USERS_REQUEST";
const ADMIN_GETS_STATISTICS_DATA = "ADMIN_GETS_STATISTICS_DATA ";
const ADMIN_GETS_ALL_USERS = " ADMIN_GETS_ALL_USERS";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAILED = "REGISTER_FAILED";
const USER_LOADED = "USER_LOADED";
const AUTH_ERROR = "AUTH_ERROR";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILED = "LOGIN_FAILED";
const LOGOUT = "LOGOUT";
const IS_LOADING = " IS_LOADING";

export {
  ADMIN_GETS_ALL_USERS_REQUEST,
  ADMIN_GETS_STATISTICS_DATA,
  ADMIN_GETS_ALL_USERS,
  REGISTER_SUCCESS,
  REGISTER_FAILED,
  USER_LOADED,
  AUTH_ERROR,
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  LOGOUT,
  IS_LOADING,
};
