const ADMIN_GETS_ALL_USERS_REQUEST = "ADMIN_GETS_ALL_USERS_REQUEST";
const ADMIN_GETS__ALL_STATISTICS_DATA = "ADMIN_GETS__ALL_STATISTICS_DATA ";
const ADMIN_GETS_ALL_USERS = " ADMIN_GETS_ALL_USERS";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAILED = "REGISTER_FAILED";
const USER_LOADED = "USER_LOADED";
const AUTH_ERROR = "AUTH_ERROR";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILED = "LOGIN_FAILED";
const IS_LOADING = " IS_LOADING";
const LOAD_USER = "LOAD_USER";
const SET_ERROR = "SET_ERROR";
const CURRENT_BOOK = "CURRENT_BOOK";
const ALL_BOOKS = "ALL_BOOKS";
const ALL_FREE_BOOKS = "ALL_FREE_BOOKS";
const UPLOAD_SPINNER = "UPLOAD_SPINNER";
const FILTRATION_RESULT = "FILTRATION_RESULT";
const FILTERED_BOOKS = "FILTERED_BOOKS";
const LOGOUT = "LOGOUT";
const FILTERED_FREE_BOOKS = "FILTERED_FREE_BOOKS";
const UPDATED_USER_INFO = "UPDATED_USER_INFO";
const UPDATED_ADMIN_INFO = "UPDATED_ADMIN_INFO";
const LOAD_ADMIN = "LOAD_ADMIN";
const SUPER_ADMIN_GETS_ALL_USERS_REQUEST = "SUPER_ADMIN_GETS_ALL_USERS_REQUEST";
const SUPER_ADMIN_GETS_ALL_USERS = "SUPER_ADMIN_GETS_ALL_USERS";
const SUPER_ADMIN_GETS_ALL_ADMIN = "SUPER_ADMIN_GETS_ALL_ADMIN";
const FILTRATION_ADMIN_RESULT = "FILTRATION_ADMIN_RESULT";
const FILTRATION_USER_RESULT = "FILTRATION_USER_RESULT";

export {
  ADMIN_GETS_ALL_USERS_REQUEST,
  SUPER_ADMIN_GETS_ALL_USERS_REQUEST,
  ADMIN_GETS__ALL_STATISTICS_DATA,
  ADMIN_GETS_ALL_USERS,
  SUPER_ADMIN_GETS_ALL_USERS,
  REGISTER_SUCCESS,
  REGISTER_FAILED,
  USER_LOADED,
  AUTH_ERROR,
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  IS_LOADING,
  LOAD_USER,
  SET_ERROR,
  CURRENT_BOOK,
  ALL_BOOKS,
  ALL_FREE_BOOKS,
  UPLOAD_SPINNER,
  FILTRATION_RESULT,
  FILTERED_BOOKS,
  LOGOUT,
  FILTERED_FREE_BOOKS,
  UPDATED_USER_INFO,
  UPDATED_ADMIN_INFO,
  LOAD_ADMIN,
  SUPER_ADMIN_GETS_ALL_ADMIN,
  FILTRATION_ADMIN_RESULT,
  FILTRATION_USER_RESULT,
};
